version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "" # Change to your desired root password
      MYSQL_DATABASE: tpfoyerr_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-tpfoyer:
    image: rymasd29/tp-foyerr:5.0.0
    depends_on:
      - mysqldb
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: >-
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/tpfoyer_db?createDatabaseIfNotExist=true",
          "spring.datasource.username": "root",
          "spring.datasource.password": "",
          "spring.jpa.show-sql": true,
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true

volumes:
  db:
